"""empty message

Revision ID: 1f2b282e1bde
Revises:
Create Date: 2019-09-20 15:09:50.863854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2b282e1bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('user', schema=None) as batch_op:
    #    batch_op.create_unique_constraint('uq_user_email', ['email'])
    #    batch_op.create_unique_constraint('uq_user_username', ['username'])

    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_role_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_role_name'), type_='unique')
        batch_op.drop_column('name')
        batch_op.drop_column('description')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')

    # ### end Alembic commands ###
