"""empty message

Revision ID: 23a7de215b98
Revises: 80eed3d524a3
Create Date: 2019-10-01 12:09:42.023427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a7de215b98'
down_revision = '80eed3d524a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placename_has_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('function', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('_placename_has_role_function_uc', ['placename_id', 'function'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placename_has_role', schema=None) as batch_op:
        batch_op.drop_constraint('_placename_has_role_function_uc', type_='unique')
        batch_op.drop_column('function')

    # ### end Alembic commands ###
