"""empty message

Revision ID: 80eed3d524a3
Revises: 
Create Date: 2019-09-23 14:34:12.390081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80eed3d524a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_has_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('function', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('_person_has_role_function_uc', ['person_id', 'function'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_has_role', schema=None) as batch_op:
        batch_op.drop_constraint('_person_has_role_function_uc', type_='unique')
        batch_op.drop_column('function')

    # ### end Alembic commands ###
