"""empty message

Revision ID: 9d5b793d0d34
Revises: 87e129cd6f97
Create Date: 2019-09-20 16:28:21.948288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5b793d0d34'
down_revision = '87e129cd6f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_has_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('function', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('_person_has_role_function_uc', ['person_id', 'function'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_has_role', schema=None) as batch_op:
        batch_op.drop_constraint('_person_has_role_function_uc', type_='unique')
        batch_op.drop_column('function')

    # ### end Alembic commands ###
